name: 'Terraform Deployment'

on:
  push:
    branches:
      - main

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  LOCATION: ${{ vars.LOCATION }}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  AKS_CLUSTER_NAME: ${{ vars.AKS_CLUSTER_NAME }}
  ACR_NAME: ${{ vars.ACR_NAME }}
  NODE_COUNT: ${{ vars.NODE_COUNT }}
  NODE_VM_SIZE: ${{ vars.NODE_VM_SIZE }}
  STORAGE_ACCOUNT_NAME: ${{ vars.STORAGE_ACCOUNT_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  STORAGE_ACCOUNT_KEY: ${{ secrets.STORAGE_ACCOUNT_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan -var="location=${{ env.LOCATION }}" -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" -var="aks_cluster_name=${{ env.AKS_CLUSTER_NAME }}" -var="acr_name=${{ env.ACR_NAME }}" -var="node_count=${{ env.NODE_COUNT }}" -var="node_vm_size=${{ env.NODE_VM_SIZE }}" -var="storage_account_name=${{ env.STORAGE_ACCOUNT_NAME }}" -var="container_name=${{ env.CONTAINER_NAME }}" -var="storage_account_key=${{ env.STORAGE_ACCOUNT_KEY }}"

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve tfplan
